#!/usr/bin/env python3
"""Generate docs/DEFERRED_VERIFICATION.md from the status tracker.

Some requirements are honestly `implemented` at a milestone's close but cannot
meet their frozen acceptance criterion until a later milestone exists — an
architecture rule with no engine to constrain, a recovery contract with no state
to recover. The tracker records those as `verification_blocked_until` plus a
`residual` naming exactly what is missing.

This document is the human-readable view of that register. It is generated and
drift-checked in CI, so the published list cannot fall behind the tracker it
claims to summarise.

Four mechanisms keep an obligation from being forgotten, and this is only the
fourth:

1. ``tools/audit_requirements.py`` hard-fails on `verified` while an obligation
   is open, which converts the anti-inflation rule from a convention into a gate;
2. ``--check-deferred M<n>`` fails if an obligation due at that milestone is
   still open when it closes, so the debt lands on the milestone that owes it;
3. every obligation carries an append-only ``deferral_history`` whose head must
   agree with the live ``verification_blocked_until``, so an obligation cannot be
   moved to a later milestone without the move itself being written down;
4. this document, so a reader can see the outstanding list without reading JSON.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))

from audit_requirements import load_json

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = "docs/DEFERRED_VERIFICATION.md"

HEADER = """\
# Deferred Verification Register

GENERATED by `tools/generate_deferred_register.py` — do not edit by hand.

Every requirement below is `implemented`: the work M0 could honestly do is done
and tested. None is `verified`, because each one's frozen acceptance criterion
names something that does not exist yet — an engine to constrain, state to
recover, a CI run to point at.

The register is not a note to self. `tools/audit_requirements.py` refuses to mark
any of these `verified` while its obligation is open, and
`tools/audit_requirements.py --check-deferred M<n>` fails the milestone that owes
the evidence if it closes without paying.

Nor can an obligation quietly slide to a later milestone. Each one carries an
append-only ledger below; the audit requires the live `verification_blocked_until`
to equal the head of that ledger, so moving a debt is itself a recorded act.
"""

EMPTY = """\
No verification obligations are outstanding.
"""


def render(reqs: list[dict[str, Any]], statuses: dict[str, dict[str, Any]]) -> str:
    titles = {r["id"]: r["title"] for r in reqs}
    acceptance = {r["id"]: r.get("acceptance", "") for r in reqs}

    rows = []
    for rid, entry in sorted(statuses.items()):
        blocked = entry.get("verification_blocked_until")
        if not blocked:
            continue
        rows.append(
            {
                "id": rid,
                "title": titles.get(rid, "(unknown requirement)"),
                "status": entry.get("status", "?"),
                "blocked": blocked,
                "residual": entry.get("residual", ""),
                "acceptance": acceptance.get(rid, ""),
                "history": entry.get("deferral_history", []),
            }
        )

    if not rows:
        return HEADER + "\n" + EMPTY

    lines = [HEADER, ""]
    by_milestone: dict[str, list[dict[str, Any]]] = {}
    for row in rows:
        by_milestone.setdefault(row["blocked"], []).append(row)

    moved = sum(1 for row in rows if len(row["history"]) > 1)
    lines.append(f"**{len(rows)} outstanding obligation(s).**")
    if moved:
        lines.append("")
        lines.append(
            f"{moved} of them has been re-dated at least once since first registered; "
            f"each move is listed under its requirement below."
        )
    lines.append("")
    lines.append("| ID | Requirement | Status | Unblocks at | Times re-dated | What is still missing |")
    lines.append("|---|---|---|---|---|---|")
    for row in rows:
        residual = row["residual"].replace("|", "\\|")
        lines.append(
            f"| {row['id']} | {row['title']} | {row['status']} | {row['blocked']} | "
            f"{max(len(row['history']) - 1, 0)} | {residual} |"
        )

    lines.append("")
    for milestone in sorted(by_milestone, key=lambda m: int(m[1:])):
        lines.append(f"## Due at {milestone}")
        lines.append("")
        for row in by_milestone[milestone]:
            lines.append(f"### {row['id']} — {row['title']}")
            lines.append("")
            lines.append(f"- **Frozen acceptance criterion:** {row['acceptance']}")
            lines.append(f"- **Residual:** {row['residual']}")
            lines.append("- **Deferral ledger:**")
            for item in row["history"]:
                lines.append(
                    f"  - {item.get('date', '?')} — dated **{item.get('blocked_until', '?')}** "
                    f"while closing {item.get('recorded_at', '?')}: {item.get('reason', '')}"
                )
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    args = parser.parse_args(argv)
    root = args.root.resolve()

    reqs = load_json(root / "requirements/requirements.json")["requirements"]
    statuses = load_json(root / "requirements/implementation_status.json")["requirements"]
    text = render(reqs, statuses)
    (root / OUTPUT).write_text(text, encoding="utf-8")

    outstanding = sum(1 for entry in statuses.values() if entry.get("verification_blocked_until"))
    print(f"Generated {OUTPUT} with {outstanding} outstanding obligation(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
