#!/usr/bin/env python3
"""Regenerate docs/TRACEABILITY_MATRIX.md from the catalogue and status tracker.

AEGIS-002. The matrix is generated, never hand-edited: CI regenerates it and
fails on any diff, so the published view of requirement coverage cannot drift
away from the tracker it claims to summarise.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))

from audit_requirements import load_json

ROOT = Path(__file__).resolve().parents[1]

HEADER = [
    "# Feature Traceability Matrix",
    "",
    "GENERATED by `tools/generate_traceability.py` — do not edit by hand.",
    "",
    "`Blocked until` names the milestone that owes the evidence a requirement still lacks;",
    "`tools/audit_requirements.py` refuses to mark such a requirement `verified`.",
    "",
    "| ID | Module | Milestone | Requirement | Status | Blocked until | Evidence |",
    "|---|---|---:|---|---|---|---|",
]


def render(reqs: list[dict[str, Any]], statuses: dict[str, dict[str, Any]]) -> str:
    lines = list(HEADER)
    for r in reqs:
        s = statuses[r["id"]]
        evidence = list(s.get("implementation", [])) + list(s.get("tests", [])) + list(s.get("reports", []))
        blocked = s.get("verification_blocked_until") or "—"
        lines.append(
            f"| {r['id']} | {r['module']} | {r['milestone']} | {r['title']} | {s['status']} | "
            f"{blocked} | {'<br>'.join(evidence) if evidence else '—'} |"
        )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    args = parser.parse_args(argv)
    root = args.root.resolve()

    reqs = load_json(root / "requirements/requirements.json")["requirements"]
    statuses = load_json(root / "requirements/implementation_status.json")["requirements"]
    (root / "docs/TRACEABILITY_MATRIX.md").write_text(render(reqs, statuses), encoding="utf-8")
    print(f"Generated traceability matrix with {len(reqs)} requirements")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
